# Generated by Django 3.2.18 on 2023-04-21 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=100)),
                ('chat_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 4, 21, 22, 18, 21, 779719))),
            ],
        ),
    ]
